### ISSUE TITLE
precision rather than nitrogendioxide_tropospheric_column

### ISSUE THREAD

**Issue by pdh21** [acgeospatial/Sentinel-5P#1]
Hi Andrew,
While using your very useful blog as a starting point to looking at Sentinel 5p data, I came across a slight error I thought I should bring to your attention.

In the description you talk about plotting nitrogendioxide_tropospheric_column, but in the code you use the uncertianty 'nitrogendioxide_tropospheric_column_precision'.
Thanks again for useful blog!
Peter Hurley

**Comment by acgeospatial** [comment]
Hi Peter, Thanks for spotting this. I have made the changes on the blog. Kind Regards Andrew
