### ISSUE TITLE
Save to Geotiff

### ISSUE THREAD

**Issue by goriliukasbuxton** [acgeospatial/Sentinel-5P#2]
Hey @acgeospatial ,
how would you save the 'no2' to Geotiff?

Thank you,

**Comment by acgeospatial** [comment]
Hi @goriliukasbuxton I am not currently working on an output function. The aim of this script is just to read the netcdf file. It should however be possible. Please search for export netcdf to geotiff in a search engine. If you come up with a solution I'd be happy to update.
