### ISSUE TITLE
OSError: [Errno -101] NetCDF: HDF error

### ISSUE THREAD

**Issue by forgetmenot9911** [acgeospatial/Sentinel-5P#4]
Hi! When I read the sentinel-5p `.nc` file, a bug below comes up: 
```shell
OSError: [Errno -101] NetCDF: HDF error: b'xxx\\S5P_OFFL_L2__NO2____20220413T040638_20220413T054808_23307_02_020301_20220414T200235.nc'
```
I want to know if you meet the same problem and hope for some advice, thanks a lot.

**Comment by acgeospatial** [comment]
It sounds like it could be a corrupt file if you are getting an error like that. This code is 4 years old so please use at your own risk
